import { Inter } from 'next/font/google'
import { PostProvider } from '../context/PostContext'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const Prompt = () => {
  
  return <>
      <div>
        <div className="flex pt-12 md:pt-6 justify-center items-center">
          <div className="md:hidden bg-blue-500 text-white p-4 rounded shadow-md fixed m-4 flex justify-center items-center space-x-6">
              <img src="https://www.orb.ac/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Forb-logo-letter-black.7a11a7c5.png&w=256&q=75" alt="Orb App Icon" className="h-8 w-10" />
              <div>
                  <p className="text-sm">Get the best experience in our app.</p>
              </div>
              <Link className='className="bg-blue-700 hover:bg-blue-800 px-3 py-1 rounded text-white text-sm' href={`https://www.orb.ac/`}>
                Open
              </Link>
          </div>
        </div>
        <div className="hidden md:block bg-gray-200 text-white p-4 rounded shadow-md fixed m-4 flex flex-col justify-center items-center px-8">
          <div className='flex justify-center items-center'>
            <img src="https://www.orb.ac/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Forb-logo-letter-black.7a11a7c5.png&w=256&q=75" alt="Orb App Icon" className="h-8 pr-2" />
            <p className="text-gray-900 text-sm">For a better experience, download our app</p>
          </div>
          <Link className='className="bg-blue-700 hover:bg-blue-400 px-3 py-1 rounded text-sm text-gray-950' href={`https://apps.apple.com/us/app/orb-everyday-web3-social-app/id1638461963`}>
            App Store
          </Link>
          <Link className='className="bg-blue-700 hover:bg-blue-400 px-3 py-1 rounded text-sm text-gray-950' href={`https://play.google.com/store/apps/details?id=app.orb.flutter`}>
            Google Play
          </Link>
        </div>
      </div>
    </>
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Prompt />
        <PostProvider>
          {children}
        </PostProvider>
      </body>
    </html>
  )
}